### ISSUE TITLE
网页自适应广告位代码 可文字 可图片

### ISSUE THREAD

**Issue by dishao123** [dishao123/dishao123.github.io#10]
双列自适应广告位代码，支持文字和图片。
`Gmeek-html<img src="https://i.111666.best/image/A5t0ISZpM80HGMY00gVlUb.jpeg">`

---

html 代码
```html
<div class="ad">
    <!--图片横幅广告-->
    <a href="https://quwan.me" target="_blank"><img src="图片地址"></a>
    <!--自适应文字广告-->
    <div class="zuo text-ad"><a href="https://quwan.me" target=" _blank"="" style="background:#01AAED;">广告招商虚位以待</a></div>
    <div class="you text-ad"><a href="https://quwan.me" target=" _blank"="" style="background:#2F4056;">广告招商虚位以待</a></div>
</div>
```

---

css 代码
```css
/**广告位CSS**/
.ad {
    background: #fff;
    overflow: hidden;
    clear: both;
    margin: 10px 0 0;
    padding: 8px;
}

.ad img {
    max-width: 100%;
}

.ad .text-ad {
    width: 50%;
}

.ad .text-ad a {
    margin: 6px 0 0;
    display: block;
    height: 60px;
    line-height: 60px;
    color: #fff;
    font-size: 24px;
    text-align: center;
}

.zuo {
    float: left;
}

.you {
    float: right;
}

@media(max-width:999px) {
    .ad .text-ad {
        width: 100%;
    }
}
```
